language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kailashkn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kailashkn/docker-react npm run test